### ISSUE TITLE
播客和社区 LOGO 收集

### ISSUE THREAD

**Issue by kang8** [opensource-f2f/partner#8]
## 图片格式

* png 或 jpg 供查看
* svg 和 ai 无损格式，利好设计师

### 播客
- [ ] #10
- [ ] #11
- [ ] #9
- [x] Go 夜聊 link to #5
- [x] Nebula Graph 星球 link to #2
- [x] #12
- [x] Web Worker link to #6
- [x] 大话开源 link to #3
- [ ] #13
- [ ] #14
- [ ] #15
- [x] #16

### 社区

- [x] #17
- [x] 大话开源 link to #3
- [ ] #18
- [x] 思否 link to #1
- [ ] #22
- [ ] #21
- [ ] #20
- [x] #19
- [ ] 小宇宙
- [ ] 津津乐道

**Comment by kang8** [comment]
Sorry, my fault, I close the wrong issue in #27 , causing this issue to close.

@LinuxSuRen  Can you reopen it? Thanks!
